# Generated by Django 5.2.10 on 2026-03-10 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanvieww', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=40)),
                ('nombre', models.CharField(max_length=100)),
                ('cargo', models.CharField(choices=[('costr', 'Costurero'), ('tapcr', 'Tapicero'), ('gerente', 'Gerente'), ('secre', 'Secretario')], default='tapcr', max_length=10)),
                ('celular', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=50)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('edad', models.IntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('tareas_realizadas', models.IntegerField()),
            ],
        ),
    ]
