# Generated by Django 6.0.2 on 2026-03-13 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanvieww', '0003_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=10)),
                ('documento', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo_producto',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.CreateModel(
            name='AnalisisFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gastos', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fuentes_ingresos', models.DecimalField(decimal_places=2, max_digits=12)),
                ('productos_vendidos', models.IntegerField()),
                ('id_administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanvieww.administrador')),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_creacion', models.TimeField()),
                ('fecha_creacion', models.DateField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanvieww.cliente')),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanvieww.empleado')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanvieww.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanvieww.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorias', models.CharField(max_length=100)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanvieww.producto')),
                ('id_inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanvieww.inventario')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_pedido', models.CharField(max_length=6)),
                ('fecha_creacion', models.DateField()),
                ('hora_creacion', models.DateTimeField()),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('evidencias', models.CharField(verbose_name=models.CharField(max_length=255))),
                ('descripcion', models.CharField(max_length=1000)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanvieww.cliente')),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanvieww.empleado')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanvieww.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('año', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('nombre_mes', models.CharField(max_length=20)),
                ('dia', models.IntegerField()),
                ('nombre_dia', models.CharField(max_length=20)),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanvieww.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='TareasPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=1000)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en progreso', 'En progreso'), ('completado', 'Completado')], default='pendiente', max_length=20)),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanvieww.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=1000)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en progreso', 'En progreso'), ('completado', 'Completado')], default='pendiente', max_length=20)),
                ('id_tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanvieww.tareaspedido')),
            ],
        ),
    ]
